/* -*- C++ -*- $Id$ */

// ******  Code generated by the The ACE ORB (TAO) IDL Compiler *******
// TAO and the TAO IDL Compiler have been developed by the Center for
// Distributed Object Computing at Washington University, St. Louis.
//
// Information about TAO is available at:
//                 http://www.cs.wustl.edu/~schmidt/TAO.html

#ifndef ECHOI_H_
#define ECHOI_H_

#if !defined (ACE_LACKS_PRAGMA_ONCE)
#pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */

#include "EchoS.h"

//Class DefaultEcho_i
class  DefaultEcho_i : public virtual POA_Echo
{
public:
  //Constructor 
  DefaultEcho_i (PortableServer::POA_ptr the_poa);
  
  //Destructor 
  virtual ~DefaultEcho_i (void);
  
virtual char * echo_it (
    const char * echo_me
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
  ));

private:

  PortableServer::POA_var the_poa_;

};


#endif /* ECHOI_H_  */
