/* -*- C++ -*- $Id$ */

// ******  Code generated by the The ACE ORB (TAO) IDL Compiler *******
// TAO and the TAO IDL Compiler have been developed by the Center for
// Distributed Object Computing at Washington University, St. Louis.
//
// Information about TAO is available at:
//                 http://www.cs.wustl.edu/~schmidt/TAO.html

#include "DefaultEcho_i.h"

// Implementation skeleton constructor
DefaultEcho_i::DefaultEcho_i (PortableServer::POA_ptr the_poa)
  : the_poa_(PortableServer::POA::_duplicate(the_poa))
  {
  }
  
// Implementation skeleton destructor
DefaultEcho_i::~DefaultEcho_i (void)
  {
  }
  
char * DefaultEcho_i::echo_it (
    const char * echo_me
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
  ))

  {
    //Add your implementation here

    try {
      // Get the object id of the target object.
      PortableServer::ObjectId_var oid = the_poa_->servant_to_id(this);
      CORBA::String_var str = PortableServer::ObjectId_to_string(oid.in());
      cout << "DefaultEcho_i::echo_it: " << str.in() << endl;

      // Echo the string passed in.
      str = CORBA::string_dup(echo_me);
      return str._retn();
    }
    catch (CORBA::Exception& ex) {
      cerr << "DefaultEcho_i::echo_it: " << endl << ex << endl;
      throw;
    }
  }
  
