#
# server.conf
#
dynamic TAO_Transport_Current_Loader Service_Object * TAO_TC:_make_TAO_Transport_Current_Loader() ""
dynamic TAO_Transport_IIOP_Current_Loader Service_Object * TAO_TC_IIOP:_make_TAO_Transport_IIOP_Current_Loader() ""
dynamic SSLIOP_Factory Service_Object *TAO_SSLIOP:_make_TAO_SSLIOP_Protocol_Factory() "-SSLAuthenticate SERVER_AND_CLIENT -SSLCertificate PEM:ssl/server-cert.pem -SSLPrivateKey PEM:ssl/server-key.pem"
static Resource_Factory "-ORBProtocolFactory SSLIOP_Factory"
#
# client.conf
#
dynamic TAO_Transport_Current_Loader Service_Object * TAO_TC:_make_TAO_Transport_Current_Loader() ""
dynamic TAO_Transport_IIOP_Current_Loader Service_Object * TAO_TC_IIOP:_make_TAO_Transport_IIOP_Current_Loader() ""
dynamic SSLIOP_Factory Service_Object *TAO_SSLIOP:_make_TAO_SSLIOP_Protocol_Factory() "-SSLAuthenticate SERVER_AND_CLIENT -SSLCertificate PEM:ssl/client-cert.pem -SSLPrivateKey PEM:ssl/client-key.pem"
static Resource_Factory "-ORBProtocolFactory SSLIOP_Factory"
