module Security {

    enum DayOfTheWeek {
      Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sun-day
    };

    struct AuditEventType {
        ExtensibleFamily    event_family;
        EventType           event_type;
    };

    typedef sequence <AuditEventType> AuditEventTypeList;

    typedef unsigned long SelectorType;

    const SelectorType    InterfaceRef = 1;
    const SelectorType    ObjectRef = 2;
    const SelectorType    Operation = 3;
    const SelectorType    Initiator = 4;
    const SelectorType    SuccessFailure = 5;
    const SelectorType    Time = 6;
    const SelectorType    DayOfWeek = 7;

};
