// The idea here is that we are trying to re-open the same module
// for our library, but our definitions are using sequences of
// standard corba strings of the same length (in the multiple
// idl definitions) even though they are called different types.
//
// In a real definition we would then go on to use these types
// in their respective interfaces etc.

#ifndef FIRST_PART_OF_MODULE_idl
#define FIRST_PART_OF_MODULE_idl

module TheFirstModule {
   // First incidental type we are defining, that would be
   // used in this IDL definition file only.

  	typedef string<32> First;

   // Would be using the "First" type here....

}; /* End TheFirstModule */

#endif // FIRST_PART_OF_MODULE_idl
