// -*- C++ -*-
//
// $Id$

// ****  Code generated by the The ACE ORB (TAO) IDL Compiler ****
// TAO and the TAO IDL Compiler have been developed by:
//       Center for Distributed Object Computing
//       Washington University
//       St. Louis, MO
//       USA
//       http://www.cs.wustl.edu/~schmidt/doc-center.html
// and
//       Distributed Object Computing Laboratory
//       University of California at Irvine
//       Irvine, CA
//       USA
//       http://doc.ece.uci.edu/
//
// Information about TAO is available at:
//     http://www.cs.wustl.edu/~schmidt/TAO.html

#ifndef _TAO_IDL_TIMEC_H_
#define _TAO_IDL_TIMEC_H_

#include "tao/corba.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#if defined (TAO_EXPORT_MACRO)
#undef TAO_EXPORT_MACRO
#endif
#define TAO_EXPORT_MACRO 

#if defined (TAO_EXPORT_NESTED_CLASSES)
#  if defined (TAO_EXPORT_NESTED_MACRO)
#    undef TAO_EXPORT_NESTED_MACRO
#  endif /* defined (TAO_EXPORT_NESTED_MACRO) */
#  define TAO_EXPORT_NESTED_MACRO 
#endif /* TAO_EXPORT_NESTED_CLASSES */

#if defined(_MSC_VER)
#if (_MSC_VER >= 1200)
#pragma warning(push)
#endif /* _MSC_VER >= 1200 */
#pragma warning(disable:4250)
#endif /* _MSC_VER */

struct TimeOfDay;
class TimeOfDay_var;

struct  TimeOfDay
{

#if !defined(__GNUC__) || !defined (ACE_HAS_GNUG_PRE_2_8)
  typedef TimeOfDay_var _var_type;
#endif /* ! __GNUC__ || g++ >= 2.8 */

  static void _tao_any_destructor (void*);

  CORBA::Short hour;
  CORBA::Short minute;
  CORBA::Short second;
};

class  TimeOfDay_var
{
public:
  TimeOfDay_var (void); // default constructor
  TimeOfDay_var (TimeOfDay *);
  TimeOfDay_var (const TimeOfDay_var &); // copy constructor
  TimeOfDay_var (const TimeOfDay &); // fixed-size types only
  ~TimeOfDay_var (void); // destructor
  
  TimeOfDay_var &operator= (TimeOfDay *);
  TimeOfDay_var &operator= (const TimeOfDay_var &);
  TimeOfDay_var &operator= (const TimeOfDay &); // fixed-size types only
  TimeOfDay *operator-> (void);
  const TimeOfDay *operator-> (void) const;
  
  operator const TimeOfDay &() const;
  operator TimeOfDay &();
  operator TimeOfDay &() const;
  
  // in, inout, out, _retn 
  const TimeOfDay &in (void) const;
  TimeOfDay &inout (void);
  TimeOfDay &out (void);
  TimeOfDay _retn (void);
  TimeOfDay *ptr (void) const;

private:
  TimeOfDay *ptr_;
};

typedef TimeOfDay &TimeOfDay_out;

extern  CORBA::TypeCode_ptr  _tc_TimeOfDay;


#if !defined (_TIME___PTR_CH_)
#define _TIME___PTR_CH_

class Time;
typedef Time *Time_ptr;

#endif /* end #if !defined */


#if !defined (_TIME___VAR_CH_)
#define _TIME___VAR_CH_

class  Time_var : public TAO_Base_var
{
public:
  Time_var (void); // default constructor
  Time_var (Time_ptr p) : ptr_ (p) {} 
  Time_var (const Time_var &); // copy constructor
  ~Time_var (void); // destructor
  
  Time_var &operator= (Time_ptr);
  Time_var &operator= (const Time_var &);
  Time_ptr operator-> (void) const;
  
  operator const Time_ptr &() const;
  operator Time_ptr &();
  // in, inout, out, _retn 
  Time_ptr in (void) const;
  Time_ptr &inout (void);
  Time_ptr &out (void);
  Time_ptr _retn (void);
  Time_ptr ptr (void) const;

private:
  Time_ptr ptr_;
  // Unimplemented - prevents widening assignment.
  Time_var (const TAO_Base_var &rhs);
  Time_var &operator= (const TAO_Base_var &rhs);
};


#endif /* end #if !defined */


#if !defined (_TIME___OUT_CH_)
#define _TIME___OUT_CH_

class  Time_out
{
public:
  Time_out (Time_ptr &);
  Time_out (Time_var &);
  Time_out (const Time_out &);
  Time_out &operator= (const Time_out &);
  Time_out &operator= (const Time_var &);
  Time_out &operator= (Time_ptr);
  operator Time_ptr &();
  Time_ptr &ptr (void);
  Time_ptr operator-> (void);
  
private:
  Time_ptr &ptr_;
};


#endif /* end #if !defined */


#if !defined (_TIME_CH_)
#define _TIME_CH_

class  Time : public virtual CORBA_Object
{
public:
#if !defined(__GNUC__) || !defined (ACE_HAS_GNUG_PRE_2_8)
  typedef Time_ptr _ptr_type;
  typedef Time_var _var_type;
#endif /* ! __GNUC__ || g++ >= 2.8 */

  // the static operations
  static Time_ptr _duplicate (Time_ptr obj);
  static Time_ptr _narrow (
      CORBA::Object_ptr obj,
      CORBA::Environment &ACE_TRY_ENV = 
        TAO_default_environment ()
    );
  static Time_ptr _unchecked_narrow (
      CORBA::Object_ptr obj,
      CORBA::Environment &ACE_TRY_ENV = 
        TAO_default_environment ()
    );
  static Time_ptr _nil (void)
    {
      return (Time_ptr)0;
    }

  static void _tao_any_destructor (void*);

  enum TimeType
  {
        EST,
        CST,
        MST,
        PST    
  };
  typedef TimeType &TimeType_out;
  static CORBA::TypeCode_ptr _tc_TimeType;

  virtual TimeOfDay get_gmt (
      
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));

  virtual Time::TimeType get_time_type (
      
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));

  virtual CORBA::Boolean _is_a (
      const CORBA::Char *type_id, 
      CORBA::Environment &ACE_TRY_ENV = 
        TAO_default_environment ()
    );
  virtual void *_tao_QueryInterface (ptr_arith_t type);
  
  virtual const char* _interface_repository_id (void) const;

protected:
  Time (void);
  Time (TAO_Stub *objref, 
      CORBA::Boolean _tao_collocated = 0
    );
  virtual ~Time (void);
private:
  Time (const Time &);
  void operator= (const Time &);  

#if (TAO_HAS_INTERCEPTORS == 1)
  // Generation of interceptors related RequestInfo classes per operation.
  // This needed to be able to store the arguments, exceptiosn, constexts
  // and build the lists dynamically on demand so that unnecessary time overhead
  // of building these lists when they arent used is avoided.
  class TAO_ClientRequest_Info_Time_get_gmt : public TAO_ClientRequest_Info
  {
  public:
    friend class Time;
    
    TAO_ClientRequest_Info_Time_get_gmt (
        const char *_tao_operation,
        IOP::ServiceContextList &_tao_service_context_list,
        CORBA::Object *_tao_target);
    
    virtual Dynamic::ParameterList * arguments (
        CORBA::Environment &ACE_TRY_ENV = 
          TAO_default_environment ()
      )
      ACE_THROW_SPEC ((CORBA::SystemException));
    
    virtual Dynamic::ExceptionList * exceptions (
        CORBA::Environment &ACE_TRY_ENV = 
          TAO_default_environment ()
      )
      ACE_THROW_SPEC ((CORBA::SystemException));
    
    virtual CORBA::Any * result (
        CORBA::Environment &ACE_TRY_ENV = 
          TAO_default_environment ()
      )
      ACE_THROW_SPEC ((CORBA::SystemException));
    
  private:
    TAO_ClientRequest_Info_Time_get_gmt (const TAO_ClientRequest_Info_Time_get_gmt &);
    void operator= (const TAO_ClientRequest_Info_Time_get_gmt &);
    void result (TimeOfDay result);
    // update the result 
    TimeOfDay result_;
  };
  
  class TAO_ClientRequest_Info_Time_get_time_type : public TAO_ClientRequest_Info
  {
  public:
    friend class Time;
    
    TAO_ClientRequest_Info_Time_get_time_type (
        const char *_tao_operation,
        IOP::ServiceContextList &_tao_service_context_list,
        CORBA::Object *_tao_target);
    
    virtual Dynamic::ParameterList * arguments (
        CORBA::Environment &ACE_TRY_ENV = 
          TAO_default_environment ()
      )
      ACE_THROW_SPEC ((CORBA::SystemException));
    
    virtual Dynamic::ExceptionList * exceptions (
        CORBA::Environment &ACE_TRY_ENV = 
          TAO_default_environment ()
      )
      ACE_THROW_SPEC ((CORBA::SystemException));
    
    virtual CORBA::Any * result (
        CORBA::Environment &ACE_TRY_ENV = 
          TAO_default_environment ()
      )
      ACE_THROW_SPEC ((CORBA::SystemException));
    
  private:
    TAO_ClientRequest_Info_Time_get_time_type (const TAO_ClientRequest_Info_Time_get_time_type &);
    void operator= (const TAO_ClientRequest_Info_Time_get_time_type &);
    void result (Time::TimeType result);
    // update the result 
    Time::TimeType result_;
  };
  
  #endif /* TAO_HAS_INTERCEPTORS */

};


#endif /* end #if !defined */

extern  CORBA::TypeCode_ptr  _tc_Time;

 void operator<<= (CORBA::Any &, const TimeOfDay &); // copying version
 void operator<<= (CORBA::Any &, TimeOfDay*); // noncopying version
 CORBA::Boolean operator>>= (const CORBA::Any &, TimeOfDay *&); // deprecated
 CORBA::Boolean operator>>= (const CORBA::Any &, const TimeOfDay *&);
extern  Time_ptr (*_TAO_collocation_Time_Stub_Factory_function_pointer) (
    CORBA::Object_ptr obj
  );
// Any operators for interface Time
 void operator<<= (CORBA::Any &, Time_ptr);
 CORBA::Boolean operator>>= (const CORBA::Any &, Time *&);
 void operator<<= (CORBA::Any &, Time::TimeType);
 CORBA::Boolean operator>>= (const CORBA::Any &, Time::TimeType &);

#ifndef __ACE_INLINE__

 CORBA::Boolean operator<< (TAO_OutputCDR &, const TimeOfDay &);
 CORBA::Boolean operator>> (TAO_InputCDR &, TimeOfDay &);
 CORBA::Boolean operator<< (TAO_OutputCDR &, const Time_ptr );
 CORBA::Boolean operator>> (TAO_InputCDR &, Time_ptr &);
 CORBA::Boolean operator<< (TAO_OutputCDR &, const Time::TimeType &); // 
 CORBA::Boolean operator>> (TAO_InputCDR &, Time::TimeType &);

#endif /* __ACE_INLINE__ */


#if defined (__ACE_INLINE__)
#include "timeC.i"
#endif /* defined INLINE */

#if defined(_MSC_VER) && (_MSC_VER >= 1200)
#pragma warning(pop)
#endif /* _MSC_VER */

#endif /* ifndef */
