dynamic SSLIOP_Factory Service_Object * TAO_SSLIOP:_make_TAO_SSLIOP_Protocol_Factory() "-SSLAuthenticate SERVER -SSLCertificate PEM:\validy\certs\wtccert.pem -SSLPrivateKey PEM:\validy\certs\private\wtckey.pem" 
dynamic Advanced_Resource_Factory Service_Object * TAO_Strategies:_make_TAO_Advanced_Resource_Factory () "-ORBProtocolFactory SSLIOP_Factory -ORBReactorType select_st -ORBInputCDRAllocator null"
static Server_Strategy_Factory "-ORBPOALock null "
