/* -*- C++ -*- $Id$ */

// ******  Code generated by the The ACE ORB (TAO) IDL Compiler *******
// TAO and the TAO IDL Compiler have been developed by the Center for
// Distributed Object Computing at Washington University, St. Louis.
//
// Information about TAO is available at:
//                 http://www.cs.wustl.edu/~schmidt/TAO.html

#include "CDBIResult.hh"

#if !defined (__ACE_INLINE__)
#include "CDBIResultC.i"
#endif /* !defined INLINE */

static const CORBA::Long _oc_ResultKind[] =
{
  TAO_ENCAP_BYTE_ORDER, // byte order
  19, ACE_NTOHL (0x49444c3a), ACE_NTOHL (0x52657375), ACE_NTOHL (0x6c744b69), ACE_NTOHL (0x6e643a31), ACE_NTOHL (0x2e300000),  // repository ID = IDL:ResultKind:1.0
  11, ACE_NTOHL (0x52657375), ACE_NTOHL (0x6c744b69), ACE_NTOHL (0x6e640000),  // name = ResultKind
  3, // member count
  7, ACE_NTOHL (0x6b526573), ACE_NTOHL (0x4f6b0000),  // name = kResOk
  9, ACE_NTOHL (0x6b526573), ACE_NTOHL (0x496e666f), ACE_NTOHL (0x0),  // name = kResInfo
  10, ACE_NTOHL (0x6b526573), ACE_NTOHL (0x46617461), ACE_NTOHL (0x6c000000),  // name = kResFatal
};
static CORBA::TypeCode _tc_TAO_tc_ResultKind (CORBA::tk_enum, sizeof (_oc_ResultKind), (char *) &_oc_ResultKind, 0, sizeof (ResultKind));
CORBA::TypeCode_ptr _tc_ResultKind = &_tc_TAO_tc_ResultKind;

static const CORBA::Long _oc_CDBIResult[] =
{
  TAO_ENCAP_BYTE_ORDER, // byte order
  19, ACE_NTOHL (0x49444c3a), ACE_NTOHL (0x43444249), ACE_NTOHL (0x52657375), ACE_NTOHL (0x6c743a31), ACE_NTOHL (0x2e300000),  // repository ID = IDL:CDBIResult:1.0
  11, ACE_NTOHL (0x43444249), ACE_NTOHL (0x52657375), ACE_NTOHL (0x6c740000),  // name = CDBIResult
  2, // member count
  9, ACE_NTOHL (0x7468655f), ACE_NTOHL (0x6b696e64), ACE_NTOHL (0x0),  // name = the_kind
  CORBA::tk_enum, // typecode kind
  92, // encapsulation length
    TAO_ENCAP_BYTE_ORDER, // byte order
    19, ACE_NTOHL (0x49444c3a), ACE_NTOHL (0x52657375), ACE_NTOHL (0x6c744b69), ACE_NTOHL (0x6e643a31), ACE_NTOHL (0x2e300000),  // repository ID = IDL:ResultKind:1.0
    11, ACE_NTOHL (0x52657375), ACE_NTOHL (0x6c744b69), ACE_NTOHL (0x6e640000),  // name = ResultKind
    3, // member count
    7, ACE_NTOHL (0x6b526573), ACE_NTOHL (0x4f6b0000),  // name = kResOk
    9, ACE_NTOHL (0x6b526573), ACE_NTOHL (0x496e666f), ACE_NTOHL (0x0),  // name = kResInfo
    10, ACE_NTOHL (0x6b526573), ACE_NTOHL (0x46617461), ACE_NTOHL (0x6c000000),  // name = kResFatal

  12, ACE_NTOHL (0x7468655f), ACE_NTOHL (0x6d657373), ACE_NTOHL (0x61676500),  // name = the_message
  CORBA::tk_string, 
  0U, // string length
};
static CORBA::TypeCode _tc_TAO_tc_CDBIResult (CORBA::tk_struct, sizeof (_oc_CDBIResult), (char *) &_oc_CDBIResult, 0, sizeof (CDBIResult));
CORBA::TypeCode_ptr _tc_CDBIResult = &_tc_TAO_tc_CDBIResult;

OutParameterTest_ptr OutParameterTest::_narrow (
    CORBA::Object_ptr obj,
    CORBA::Environment &ACE_TRY_ENV
  )
{
  if (CORBA::is_nil (obj))
    return OutParameterTest::_nil ();
  CORBA::Boolean is_a = obj->_is_a ("IDL:OutParameterTest:1.0", ACE_TRY_ENV);
  ACE_CHECK_RETURN (OutParameterTest::_nil ());
  if (is_a == 0)
    return OutParameterTest::_nil ();
  return OutParameterTest::_unchecked_narrow (obj, ACE_TRY_ENV);
}

OutParameterTest_ptr OutParameterTest::_unchecked_narrow (
    CORBA::Object_ptr obj,
    CORBA::Environment &
  )
{
  if (CORBA::is_nil (obj))
    return OutParameterTest::_nil ();
  TAO_Stub* stub = obj->_stubobj ();
  stub->_incr_refcnt ();
  OutParameterTest_ptr default_proxy = OutParameterTest::_nil ();
  if (obj->_is_collocated () && _TAO_collocation_OutParameterTest_Stub_Factory_function_pointer != 0)
    {
      default_proxy = _TAO_collocation_OutParameterTest_Stub_Factory_function_pointer (obj);
    }
  if (CORBA::is_nil (default_proxy))
    ACE_NEW_RETURN (default_proxy, OutParameterTest (stub), OutParameterTest::_nil ());
  return TAO_OutParameterTest_PROXY_FACTORY_ADAPTER::instance ()->create_proxy (default_proxy);
}

OutParameterTest_ptr 
OutParameterTest::_duplicate (OutParameterTest_ptr obj)
{
  if (!CORBA::is_nil (obj))
    obj->_incr_refcnt ();
  return obj;
}

char * OutParameterTest::mytest (
    CDBIResult_out the_info
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
  ))
{
  ACE_DECLARE_NEW_CORBA_ENV;
  CORBA::String_var _tao_safe_retval;
  
  
  TAO_Stub *istub = this->_stubobj ();
  if (istub == 0)
    ACE_THROW_RETURN (CORBA::INTERNAL (), 0);

  
  ACE_NEW_RETURN (the_info.ptr (), CDBIResult, _tao_retval);
  TAO_GIOP_Twoway_Invocation _tao_call (
      istub,
      "mytest",
      6,
      istub->orb_core ()
    );

#if defined (TAO_HAS_INTERCEPTORS)
    TAO_ClientRequestInterceptor_Adapter
      _tao_vfr (istub->orb_core ()->orb ()->_get_client_interceptor (ACE_TRY_ENV));
    ACE_CHECK_RETURN (0);
    PortableInterceptor::Cookies _tao_cookies;
    CORBA::NVList_var _tao_interceptor_args;
    if (_tao_vfr.valid ())
      {
        istub->orb_core ()->orb ()->create_list (0, _tao_interceptor_args.inout (), ACE_TRY_ENV);
        ACE_CHECK_RETURN (0);
      }

    ACE_TRY
      {
#endif /* TAO_HAS_INTERCEPTORS */

      for (;;)
      {
        _tao_call.start (ACE_TRY_ENV);
        TAO_INTERCEPTOR_CHECK_RETURN (0);

        TAO_INTERCEPTOR (
            _tao_vfr.preinvoke (
                _tao_call.request_id (),
                1,
                this,
                "mytest",
                _tao_call.service_info (),
                _tao_interceptor_args.inout (),
                _tao_cookies,
                ACE_TRY_ENV
              )
          );
        TAO_INTERCEPTOR_CHECK_RETURN (0);
        CORBA::Short flag = 131;
        // Tremporary hack until GIOP 1.2 is implemented.
        
        _tao_call.prepare_header (ACE_static_cast (CORBA::Octet, flag), ACE_TRY_ENV);
        TAO_INTERCEPTOR_CHECK_RETURN (0);

        int _invoke_status =
          _tao_call.invoke (0, 0, ACE_TRY_ENV);
                TAO_INTERCEPTOR_CHECK_RETURN (0);

        if (_invoke_status == TAO_INVOKE_RESTART)
          continue;
        if (_invoke_status != TAO_INVOKE_OK)
        {
          TAO_INTERCEPTOR_THROW_RETURN (CORBA::UNKNOWN (TAO_DEFAULT_MINOR_CODE, CORBA::COMPLETED_YES), 0);

        }
        TAO_InputCDR &_tao_in = _tao_call.inp_stream ();
        if (!(
              (_tao_in >> _tao_safe_retval.inout ()) &&
              (_tao_in >> *the_info.ptr ())
          ))
          TAO_INTERCEPTOR_THROW_RETURN (CORBA::MARSHAL (TAO_DEFAULT_MINOR_CODE, CORBA::COMPLETED_YES), 0);

        TAO_INTERCEPTOR (
            _tao_vfr.postinvoke (
                _tao_call.request_id (),
                1,
                this,
                "mytest",
                _tao_call.service_info (),
                _tao_interceptor_args.inout (),
                _tao_cookies,
                ACE_TRY_ENV
              )
          );
        TAO_INTERCEPTOR_CHECK_RETURN (0);
        break;
        
      }
#if defined (TAO_HAS_INTERCEPTORS)
      
    }
  ACE_CATCHANY
    {
      _tao_vfr.exception_occurred (
          _tao_call.request_id (),
          1,
          this,
          "mytest",
          _tao_cookies,
          ACE_TRY_ENV
        );
      ACE_RETHROW;
    }
  ACE_ENDTRY;
  ACE_CHECK_RETURN (0);
#endif /* TAO_HAS_INTERCEPTORS */
  return _tao_safe_retval._retn ();
}

CORBA::Boolean OutParameterTest::_is_a (const CORBA::Char *value, CORBA::Environment &ACE_TRY_ENV)
{
  if (
    (!ACE_OS::strcmp ((char *)value, "IDL:OutParameterTest:1.0")) ||
    (!ACE_OS::strcmp ((char *)value, "IDL:omg.org/CORBA/Object:1.0")))
  return 1; // success using local knowledge
  else
    return this->CORBA_Object::_is_a (value, ACE_TRY_ENV);
}

const char* OutParameterTest::_interface_repository_id (void) const
{
  return "IDL:OutParameterTest:1.0";
}

TAO_OutParameterTest_Default_Proxy_Factory::TAO_OutParameterTest_Default_Proxy_Factory (int register_proxy_factory)
{
  if (register_proxy_factory)
    {
      TAO_OutParameterTest_PROXY_FACTORY_ADAPTER::instance ()->register_proxy_factory (this);
    }
}

TAO_OutParameterTest_Default_Proxy_Factory::~TAO_OutParameterTest_Default_Proxy_Factory (void)
{
}

OutParameterTest_ptr
TAO_OutParameterTest_Default_Proxy_Factory::create_proxy (
    ::OutParameterTest_ptr proxy,
    CORBA::Environment &
  )
{
  return proxy;
}

TAO_OutParameterTest_Proxy_Factory_Adapter::TAO_OutParameterTest_Proxy_Factory_Adapter (void)
   : proxy_factory_ (0),
     delete_proxy_factory_ (0)
{
}

TAO_OutParameterTest_Proxy_Factory_Adapter::~TAO_OutParameterTest_Proxy_Factory_Adapter (void)
{
  // Making sure the factory which the adapter has is destroyed with it.
  if (this->proxy_factory_ != 0)
    delete this->proxy_factory_;
}

int
TAO_OutParameterTest_Proxy_Factory_Adapter::register_proxy_factory (
  TAO_OutParameterTest_Default_Proxy_Factory *df,
     CORBA::Environment &ACE_TRY_ENV
      )
{
  ACE_MT (ACE_GUARD_RETURN (ACE_Recursive_Thread_Mutex, ace_mon,
    this->lock_, 0));
  // Remove any existing <proxy_factory_> and replace with the new one.
  this->unregister_proxy_factory (ACE_TRY_ENV);
  this->proxy_factory_ = df;
  this->delete_proxy_factory_ = 0;
return 0;
}

int
TAO_OutParameterTest_Proxy_Factory_Adapter::unregister_proxy_factory (
  CORBA::Environment &
    )
{
  ACE_MT (ACE_GUARD_RETURN (ACE_Recursive_Thread_Mutex, ace_mon,
    this->lock_, 0));
  if (this->delete_proxy_factory_ == 0 && this->proxy_factory_ != 0)
    {
      // Its necessary to set <delete_proxy_factory_> to 1 to make sure that it
      // doesnt get into an infinite loop in <unregister_proxy_factory> as it is 
      // invoked in the destructor of the class too.
      this->delete_proxy_factory_ = 1;
      delete this->proxy_factory_;
      this->proxy_factory_ = 0;
    }
return 0;
}

OutParameterTest_ptr
TAO_OutParameterTest_Proxy_Factory_Adapter::create_proxy (
    ::OutParameterTest_ptr proxy,
    CORBA::Environment &
  )
{
  ACE_MT (ACE_GUARD_RETURN (ACE_Recursive_Thread_Mutex, ace_mon,
    this->lock_, 0));
  // Verify that an <proxy_factory_> is available else make one.
  if (this->proxy_factory_ == 0)
    ACE_NEW_RETURN (this->proxy_factory_,
        TAO_OutParameterTest_Default_Proxy_Factory (1), 
         0);
      
    
  return this->proxy_factory_->create_proxy (proxy);
}

TAO_OutParameterTest_Smart_Proxy_Base::TAO_OutParameterTest_Smart_Proxy_Base (::OutParameterTest_ptr proxy)
: base_proxy_ (proxy)
{
}

TAO_OutParameterTest_Smart_Proxy_Base::~TAO_OutParameterTest_Smart_Proxy_Base (void)
{
}

char * TAO_OutParameterTest_Smart_Proxy_Base::mytest  (
    CDBIResult_out the_info
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
  ))
{
  return this->base_proxy_->mytest (
      the_info
    );

}

#if defined (ACE_HAS_EXPLICIT_TEMPLATE_INSTANTIATION) || \
  defined (ACE_HAS_GNU_REPO)
template class ACE_Singleton<TAO_OutParameterTest_Proxy_Factory_Adapter, ACE_SYNCH_RECURSIVE_MUTEX >;
#elif defined (ACE_HAS_TEMPLATE_INSTANTIATION_PRAGMA)
#pragma instantiate ACE_Singleton<TAO_OutParameterTest_Proxy_Factory_Adapter, ACE_SYNCH_RECURSIVE_MUTEX>
#endif /* ACE_HAS_EXPLICIT_TEMPLATE_INSTANTIATION */

static const CORBA::Long _oc_OutParameterTest[] =
{
  TAO_ENCAP_BYTE_ORDER, // byte order
  25, ACE_NTOHL (0x49444c3a), ACE_NTOHL (0x4f757450), ACE_NTOHL (0x6172616d), ACE_NTOHL (0x65746572), ACE_NTOHL (0x54657374), ACE_NTOHL (0x3a312e30), ACE_NTOHL (0x0),  // repository ID = IDL:OutParameterTest:1.0
  17, ACE_NTOHL (0x4f757450), ACE_NTOHL (0x6172616d), ACE_NTOHL (0x65746572), ACE_NTOHL (0x54657374), ACE_NTOHL (0x0),  // name = OutParameterTest
};
static CORBA::TypeCode _tc_TAO_tc_OutParameterTest (CORBA::tk_objref, sizeof (_oc_OutParameterTest), (char *) &_oc_OutParameterTest, 0, sizeof (OutParameterTest));
CORBA::TypeCode_ptr _tc_OutParameterTest = &_tc_TAO_tc_OutParameterTest;

void operator<<= (CORBA::Any &_tao_any, ResultKind _tao_elem)
{
  ResultKind *_tao_any_val;
  ACE_NEW (_tao_any_val, ResultKind (_tao_elem));
  if (!_tao_any_val) return;
  ACE_TRY_NEW_ENV
  {
    TAO_OutputCDR stream;
    stream << *_tao_any_val;
    _tao_any._tao_replace (
        _tc_ResultKind,
        TAO_ENCAP_BYTE_ORDER,
        stream.begin (),
        1,
        _tao_any_val,
        ACE_TRY_ENV
      );
    ACE_TRY_CHECK;
  }
  ACE_CATCHANY
  {
    // free allocated storage
    delete _tao_any_val;
  }
  ACE_ENDTRY;
}

CORBA::Boolean operator>>= (const CORBA::Any &_tao_any, ResultKind &_tao_elem)
{
  ACE_TRY_NEW_ENV
  {
    CORBA::TypeCode_var type = _tao_any.type ();
    if (!type->equivalent (_tc_ResultKind, ACE_TRY_ENV)) // not equal
      {
        return 0;
      }
    ACE_TRY_CHECK;
    TAO_InputCDR stream (
        _tao_any._tao_get_cdr (),
        _tao_any._tao_byte_order ()
      );
    if (stream >> _tao_elem)
    {
      return 1;
    }
  }
  ACE_CATCHANY
  {
    return 0;
  }
  ACE_ENDTRY;
  return 0;
}

void operator<<= (CORBA::Any &_tao_any, const CDBIResult &_tao_elem) // copying
{
  CDBIResult *_any_val = 0;
  ACE_NEW (_any_val, CDBIResult (_tao_elem));
  if (!_any_val) return;
  ACE_TRY_NEW_ENV
  {
    TAO_OutputCDR stream;
    stream << *_any_val;
    _tao_any._tao_replace (
        _tc_CDBIResult,
        TAO_ENCAP_BYTE_ORDER,
        stream.begin (),
        1,
        _any_val,
        ACE_TRY_ENV
      );
    ACE_TRY_CHECK;
  }
  ACE_CATCHANY
  {
    delete _any_val;
  }
  ACE_ENDTRY;
}

void operator<<= (CORBA::Any &_tao_any, CDBIResult *_tao_elem) // non copying
{
  ACE_TRY_NEW_ENV
  {
    TAO_OutputCDR stream;
    stream << *_tao_elem;
    _tao_any._tao_replace (
        _tc_CDBIResult,
        TAO_ENCAP_BYTE_ORDER,
        stream.begin (),
        1,
        _tao_elem,
        ACE_TRY_ENV
      );
    ACE_TRY_CHECK;
  }
  ACE_CATCHANY
  {
    delete _tao_elem;
    _tao_elem = 0;
  }
  ACE_ENDTRY;
}

CORBA::Boolean operator>>= (const CORBA::Any &_tao_any, CDBIResult *&_tao_elem)
{
  ACE_TRY_NEW_ENV
  {
    CORBA::TypeCode_var type = _tao_any.type ();
    if (!type->equivalent (_tc_CDBIResult, ACE_TRY_ENV)) // not equal
      {
        _tao_elem = 0;
        return 0;
      }
    ACE_TRY_CHECK;
    if (_tao_any.any_owns_data ())
    {
      _tao_elem = (CDBIResult *)_tao_any.value ();
      return 1;
    }
    else
    {
      ACE_NEW_RETURN (_tao_elem, CDBIResult, 0);
      TAO_InputCDR stream (
          _tao_any._tao_get_cdr (),
          _tao_any._tao_byte_order ()
        );
      if (stream >> *_tao_elem)
      {
        ((CORBA::Any *)&_tao_any)->_tao_replace (
            _tc_CDBIResult,
            1,
            ACE_reinterpret_cast (void *, _tao_elem),
            ACE_TRY_ENV
          );
        ACE_TRY_CHECK;
        return 1;
      }
      else
      {
        delete _tao_elem;
        _tao_elem = 0;
      }
    }
  }
  ACE_CATCHANY
  {
    delete _tao_elem;
    _tao_elem = 0;
    return 0; 
  }
  ACE_ENDTRY;
  return 0;
}

CORBA::Boolean operator>>= (const CORBA::Any &_tao_any, const CDBIResult *&_tao_elem)
{
  ACE_TRY_NEW_ENV
  {
    CORBA::TypeCode_var type = _tao_any.type ();
    if (!type->equivalent (_tc_CDBIResult, ACE_TRY_ENV)) // not equal
      {
        _tao_elem = 0;
        return 0;
      }
    ACE_TRY_CHECK;
    if (_tao_any.any_owns_data ())
    {
      _tao_elem = (CDBIResult *)_tao_any.value ();
      return 1;
      }
    else
    {
      ACE_NEW_RETURN (_tao_elem, CDBIResult, 0);
      TAO_InputCDR stream (
          _tao_any._tao_get_cdr (),
          _tao_any._tao_byte_order ()
        );
      if (stream >> *(CDBIResult *)_tao_elem)
      {
        ((CORBA::Any *)&_tao_any)->_tao_replace (
            _tc_CDBIResult,
            1,
            ACE_reinterpret_cast (void *, ACE_const_cast (CDBIResult *&, _tao_elem)),
            ACE_TRY_ENV
          );
        ACE_TRY_CHECK;
        return 1;
      }
      else
      {
        delete ACE_const_cast (CDBIResult *&, _tao_elem);
        _tao_elem = 0;
      }
    }
  }
  ACE_CATCHANY
  {
    delete ACE_const_cast (CDBIResult *&, _tao_elem);
    _tao_elem = 0;
    return 0; 
  }
  ACE_ENDTRY;
  return 0;
}

OutParameterTest_ptr (*_TAO_collocation_OutParameterTest_Stub_Factory_function_pointer) (
    CORBA::Object_ptr obj
  ) = 0;
void operator<<= (CORBA::Any &_tao_any, OutParameterTest_ptr _tao_elem)
{
  CORBA::Object_ptr *_tao_obj_ptr = 0;
  ACE_TRY_NEW_ENV
  {
    ACE_NEW (_tao_obj_ptr, CORBA::Object_ptr);
    *_tao_obj_ptr = OutParameterTest::_duplicate (_tao_elem);
    TAO_OutputCDR stream;
    if (stream << *_tao_obj_ptr)
    {
      _tao_any._tao_replace (
          _tc_OutParameterTest, 
          TAO_ENCAP_BYTE_ORDER,
          stream.begin (),
          1,
          _tao_obj_ptr,
          ACE_TRY_ENV
        );
      ACE_TRY_CHECK;
    }
    else
    {
      delete _tao_obj_ptr;
    }
  }
  ACE_CATCHANY
  {
    delete _tao_obj_ptr;
  }
  ACE_ENDTRY;
}

CORBA::Boolean operator>>= (const CORBA::Any &_tao_any, OutParameterTest_ptr &_tao_elem)
{
  CORBA::Object_ptr *tmp = 0;
  ACE_NEW_RETURN (tmp, CORBA::Object_ptr, 0);
  ACE_TRY_NEW_ENV
  {
    _tao_elem = OutParameterTest::_nil ();
    CORBA::TypeCode_var type = _tao_any.type ();
    if (!type->equivalent (_tc_OutParameterTest, ACE_TRY_ENV)) // not equal
      {
        delete tmp;
        return 0;
      }
    ACE_TRY_CHECK;
    TAO_InputCDR stream (
        _tao_any._tao_get_cdr (),
        _tao_any._tao_byte_order ()
      );
    CORBA::Object_var _tao_obj_var;
    if (stream >> _tao_obj_var.out ())
    {
      _tao_elem = OutParameterTest::_narrow (_tao_obj_var.in (), ACE_TRY_ENV);
      ACE_TRY_CHECK;
      *tmp = (CORBA::Object_ptr) _tao_elem;  // any owns the object
      ((CORBA::Any *)&_tao_any)->_tao_replace (
          _tc_OutParameterTest,
          1,
          tmp,
          ACE_TRY_ENV
        );
      ACE_TRY_CHECK;
      return 1;
    }
    else    // failure
    {
      delete tmp;
    }
  }
  ACE_CATCHANY
  {
    delete tmp;
    _tao_elem = OutParameterTest::_nil ();
    return 0;
  }
  ACE_ENDTRY;
  _tao_elem = OutParameterTest::_nil ();
  return 0;
}

#if defined (ACE_HAS_EXPLICIT_TEMPLATE_INSTANTIATION)  || \
    defined (ACE_HAS_GNU_REPO)
    template class TAO_Object_Field_T<OutParameterTest,OutParameterTest_var>;
  template class TAO_Object_Manager<OutParameterTest,OutParameterTest_var>;
#elif defined (ACE_HAS_TEMPLATE_INSTANTIATION_PRAGMA)
#  pragma instantiate TAO_Object_Field_T<OutParameterTest,OutParameterTest_var>
#  pragma instantiate TAO_Object_Manager<OutParameterTest,OutParameterTest_var>
#endif /* ACE_HAS_EXPLICIT_TEMPLATE_INSTANTIATION */

